author: marjamis
repository: marjamis/marjamis.github.io
theme: jekyll-theme-hacker
# Leaving as unspecified as my default layout is more basic that the default from the theme at this point of time
# defaults:
#   - scope:
#       path: "" # an empty string here means all files in the project
#     values:
#       layout: "default"
timezone: Australia/Sydney

collections:
  pages:
    output: true
  slides:
    output: true

# Additional non-standard Github plugins
plugin:
  - jekyll-feed

readme_index:
  enabled: true
