name: Lighthouse

on:
  push:
    branches:
      - main

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: mkdir -p ${{ github.workspace }}/tmp/artifacts

      - name: Lighthouse
        uses: foo-software/lighthouse-check-action@v9.1.1
        id: lighthouseCheck
        with:
          outputDirectory: ${{ github.workspace }}/tmp/artifacts
          urls: "https://marjamis.github.io"

      - name: Upload artifacts
        uses: actions/upload-artifact@v3.1.2
        with:
          name: Lighthouse reports
          path: ${{ github.workspace }}/tmp/artifacts

      - name: Verify Lighthouse Check results
        uses: foo-software/lighthouse-check-status-action@v2.0.1
        with:
          lighthouseCheckResults: ${{ steps.lighthouseCheck.outputs.lighthouseCheckResults }}
          minAccessibilityScore: "90"
          minBestPracticesScore: "90"
          minPerformanceScore: "80"
          minSeoScore: "90"
