name: Links validator

on: 
 schedule:
   - cron:  '0 9 * * 1'

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Check links
        uses: lycheeverse/lychee-action@f1da3291e1d03cbe11a413ae9f16b62fec99e6b6 # 1.4.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: --verbose --no-progress --timeout 10 --max-concurrency 2 **/*.md
      
      - name: Get current date
        id: date
        run: echo "::set-output name=now::$(date +'%d-%m-%Y')"
        
      - name: Create Issue From File
        uses: peter-evans/create-issue-from-file@v4.0.0

        with:
          title: Automated Links Checker Report for ${{ steps.date.outputs.now }}
          content-filepath: ./lychee/out.md
          labels: links validator
