name: Links validator

on:
  schedule:
    - cron: "0 9 * * 1"
  push:
    branches:
      - main

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v2.9.0
        with:
          args: --no-progress --timeout 10 --max-concurrency 2 --max-redirects 10 -u "Mozilla/5.0 Gecko/20100101 Firefox/120.0" **/*.md
          fail: false

      - name: Get current date
        id: date
        run: echo "now=$(date +'%d-%m-%Y')" >> $GITHUB_OUTPUT

      - name: Create Issue From File
        if: steps.lychee.outputs.exit_code != 0
        uses: peter-evans/create-issue-from-file@v6
        with:
          title: Automated Links Checker Report for ${{ steps.date.outputs.now }}
          content-filepath: ./lychee/out.md
          labels: links validator, report, automated issue
