name: Links validator

on:
  schedule:
    - cron: "0 9 * * 1"
  push:
    branches:
      - master

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v1.5.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: --verbose --no-progress --timeout 10 --max-concurrency 2 **/*.md

      - name: Get current date
        id: date
        run: echo "now=$(date +'%d-%m-%Y')" >> $GITHUB_OUTPUT

      - name: Create Issue From File
        if: env.lychee_exit_code != 0
        uses: peter-evans/create-issue-from-file@v4.0.0

        with:
          title: Automated Links Checker Report for ${{ steps.date.outputs.now }}
          content-filepath: ./lychee/out.md
          labels: links validator, report, automated issue
